export const AUTH_ACTION_TYPES = {
    REGISTER_REQUEST: 'CLIENTS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'CLIENTS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'CLIENTS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'CLIENTS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'CLIENTS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'CLIENTS_LOGIN_FAILURE',
    
    LOGOUT: 'CLIENTS_LOGOUT'
};